### ISSUE TITLE
Fix autoload issue

### ISSUE THREAD

**Issue by tollebrandon** [deriegle/rails_starter_project#1]
I found the issue. https://blog.bigbinary.com/2016/08/29/rails-5-disables-autoloading-after-booting-the-app-in-production.html

You can replace with `config.eager_load_paths << Rails.root.join('lib')` and it will work no problwm.  https://github.com/deriegle/rails_starter_project/blob/03d2124e820da5f0d627973185568348faea508f/config/application.rb#L27

**Comment by deriegle** [comment]
Thanks for finding this @tollebrandon! I just merged a fix for this issue in #2.
